// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyTypeSystem.h"
#include "ManiacManfredTypeSystem.generated.h"

/** Articy Type System */
UCLASS(BlueprintType)
class MANIACMANFRED_API UManiacManfredTypeSystem : public UArticyTypeSystem
{
	GENERATED_BODY()
	
};
